# Generated by Django 4.1.13 on 2024-01-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Did', models.IntegerField()),
                ('Dname', models.CharField(max_length=25)),
                ('Duse', models.CharField(max_length=25)),
            ],
        ),
    ]
